class EvidenceCategories {
  // Map struktur: Kategori -> Jenis -> List<SubJenis>
  static const Map<String, Map<String, List<String>>> categories = {
    'foto': {
      'Foto Milestone Barang': [
        'Packing Barang',
        'Keberangkatan Barang',
        'Kedatangan Barang',
        'Venue Proses Install CAT OS',
      ],
      'Foto Milestone SDM': [
        'Keberangkatan SDM',
        'Kedatangan SDM',
        'Kepulangan SDM',
      ],
      'Foto Absen': [
        'Absen Pagi Hari Pertama',
        'Absen Sore Hari Pertama',
        'Absen Pagi Hari Kedua',
        'Absen Sore Hari Kedua',
        'Absen Pagi Hari Ketiga',
        'Absen Sore Hari Ketiga',
        'Absen Pagi Hari Keempat',
        'Absen Sore Hari Keempat',
        'Absen Pagi Hari Kelima',
        'Absen Sore Hari Kelima',
        'Absen Pagi Hari Keenam',
        'Absen Sore Hari Keenam',
        'Absen Pagi Hari Ketujuh',
        'Absen Sore Hari Ketujuh',
        'Absen Pagi Hari Kedelapan',
        'Absen Sore Hari Kedelapan',
        'Absen Pagi Hari Kesembilan',
        'Absen Sore Hari Kesembilan',
        'Absen Pagi Hari Kesepuluh',
        'Absen Sore Hari Kesepuluh',
        'Absen Pagi Hari Kesebelas',
        'Absen Sore Hari Kesebelas',
      ],
      'Foto Harian': [
        'Sesi 1 Hari Pertama',
        'Sesi 2 Hari Pertama',
        'Sesi 3 Hari Pertama',
        'Sesi 4 Hari Pertama',
        'Sesi 1 Hari Kedua',
        'Sesi 2 Hari Kedua',
        'Sesi 3 Hari Kedua',
        'Sesi 4 Hari Kedua',
        'Sesi 1 Hari Ketiga',
        'Sesi 2 Hari Ketiga',
        'Sesi 3 Hari Ketiga',
        'Sesi 4 Hari Ketiga',
        'Sesi 1 Hari Keempat',
        'Sesi 2 Hari Keempat',
        'Sesi 3 Hari Keempat',
        'Sesi 4 Hari Keempat',
        'Sesi 1 Hari Kelima',
        'Sesi 2 Hari Kelima',
        'Sesi 3 Hari Kelima',
        'Sesi 4 Hari Kelima',
        'Sesi 1 Hari Keenam',
        'Sesi 2 Hari Keenam',
        'Sesi 3 Hari Keenam',
        'Sesi 4 Hari Keenam',
        'Sesi 1 Hari Ketujuh',
        'Sesi 2 Hari Ketujuh',
        'Sesi 3 Hari Ketujuh',
        'Sesi 4 Hari Ketujuh',
        'Sesi 1 Hari Kedelapan',
        'Sesi 2 Hari Kedelapan',
        'Sesi 3 Hari Kedelapan',
        'Sesi 4 Hari Kedelapan',
        'Sesi 1 Hari Kesembilan',
        'Sesi 2 Hari Kesembilan',
        'Sesi 3 Hari Kesembilan',
        'Sesi 4 Hari Kesembilan',
        'Sesi 1 Hari Kesepuluh',
        'Sesi 2 Hari Kesepuluh',
        'Sesi 3 Hari Kesepuluh',
        'Sesi 4 Hari Kesepuluh',
        'Sesi 1 Hari Kesebelas',
        'Sesi 2 Hari Kesebelas',
        'Sesi 3 Hari Kesebelas',
        'Sesi 4 Hari Kesebelas',
        'Sesi 1 Hari Kedua Belas',
        'Sesi 2 Hari Kedua Belas',
        'Sesi 3 Hari Kedua Belas',
        'Sesi 4 Hari Kedua Belas',
        'Sesi 1 Hari Ketiga Belas',
        'Sesi 2 Hari Ketiga Belas',
        'Sesi 3 Hari Ketiga Belas',
        'Sesi 4 Hari Ketiga Belas',
        'Sesi 1 Hari Keempat Belas',
        'Sesi 2 Hari Keempat Belas',
        'Sesi 3 Hari Keempat Belas',
        'Sesi 4 Hari Keempat Belas',
        'Sesi 1 Hari Kelima Belas',
        'Sesi 2 Hari Kelima Belas',
        'Sesi 3 Hari Kelima Belas',
        'Sesi 4 Hari Kelima Belas',
        'Sesi 1 Hari Keenam Belas',
        'Sesi 2 Hari Keenam Belas',
        'Sesi 3 Hari Keenam Belas',
        'Sesi 4 Hari Keenam Belas',
        'Sesi 1 Hari Ketujuh Belas',
        'Sesi 2 Hari Ketujuh Belas',
        'Sesi 3 Hari Ketujuh Belas',
        'Sesi 4 Hari Ketujuh Belas',
        'Sesi 1 Hari Kedelapan Belas',
        'Sesi 2 Hari Kedelapan Belas',
        'Sesi 3 Hari Kedelapan Belas',
        'Sesi 4 Hari Kedelapan Belas',
      ],
      'Foto Perangkat': [
        'Perangkat',
      ],
    },
    'video': {
      'Video Uji Fungsi': [
        'Video Uji Fungsi',
      ],
      'Video Barang': [
        'Hari Pertama',
        'Hari Kedua',
        'Hari Ketiga',
        'Hari Keempat',
        'Hari Kelima',
        'Hari Keenam',
        'Hari Ketujuh',
        'Hari Kedelapan',
        'Hari Kesembilan',
        'Hari Kesepuluh',
        'Hari Kesebelas',
        'Hari Kedua Belas',
        'Hari Ketiga Belas',
        'Hari Keempat Belas',
        'Hari Kelima Belas',
        'Hari Keenam Belas',
        'Hari Ketujuh Belas',
        'Hari Kedelapan Belas',
      ],
      'Video Sesi': [
        '1 Hari Pertama',
        '2 Hari Pertama',
        '3 Hari Pertama',
        '4 Hari Pertama',
        '1 Hari Kedua',
        '2 Hari Kedua',
        '3 Hari Kedua',
        '4 Hari Kedua',
        '1 Hari Ketiga',
        '2 Hari Ketiga',
        '3 Hari Ketiga',
        '4 Hari Ketiga',
        '1 Hari Keempat',
        '2 Hari Keempat',
        '3 Hari Keempat',
        '4 Hari Keempat',
        '1 Hari Kelima',
        '2 Hari Kelima',
        '3 Hari Kelima',
        '4 Hari Kelima',
        '1 Hari Keenam',
        '2 Hari Keenam',
        '3 Hari Keenam',
        '4 Hari Keenam',
        '1 Hari Ketujuh',
        '2 Hari Ketujuh',
        '3 Hari Ketujuh',
        '4 Hari Ketujuh',
        '1 Hari Kedelapan',
        '2 Hari Kedelapan',
        '3 Hari Kedelapan',
        '4 Hari Kedelapan',
        '1 Hari Kesembilan',
        '2 Hari Kesembilan',
        '3 Hari Kesembilan',
        '4 Hari Kesembilan',
        '1 Hari Kesepuluh',
        '2 Hari Kesepuluh',
        '3 Hari Kesepuluh',
        '4 Hari Kesepuluh',
        '1 Hari Kesebelas',
        '2 Hari Kesebelas',
        '3 Hari Kesebelas',
        '4 Hari Kesebelas',
        '1 Hari Kedua Belas',
        '2 Hari Kedua Belas',
        '3 Hari Kedua Belas',
        '4 Hari Kedua Belas',
        '1 Hari Ketiga Belas',
        '2 Hari Ketiga Belas',
        '3 Hari Ketiga Belas',
        '4 Hari Ketiga Belas',
        '1 Hari Keempat Belas',
        '2 Hari Keempat Belas',
        '3 Hari Keempat Belas',
        '4 Hari Keempat Belas',
        '1 Hari Kelima Belas',
        '2 Hari Kelima Belas',
        '3 Hari Kelima Belas',
        '4 Hari Kelima Belas',
        '1 Hari Keenam Belas',
        '2 Hari Keenam Belas',
        '3 Hari Keenam Belas',
        '4 Hari Keenam Belas',
        '1 Hari Ketujuh Belas',
        '2 Hari Ketujuh Belas',
        '3 Hari Ketujuh Belas',
        '4 Hari Ketujuh Belas',
        '1 Hari Kedelapan Belas',
        '2 Hari Kedelapan Belas',
        '3 Hari Kedelapan Belas',
        '4 Hari Kedelapan Belas',
      ],
      'Video Vlog': [
        'Video Vlog',
      ],
    },
  };

  // Get list jenis berdasarkan kategori
  static List<String> getJenisByKategori(String kategori) {
    final kategoriKey = kategori.toLowerCase();
    return categories[kategoriKey]?.keys.toList() ?? [];
  }

  // Get list sub jenis berdasarkan kategori dan jenis
  static List<String> getSubJenisByJenis(String kategori, String jenis) {
    final kategoriKey = kategori.toLowerCase();
    return categories[kategoriKey]?[jenis] ?? [];
  }

  // Check apakah kategori punya jenis/sub jenis
  static bool hasJenisSubJenis(String kategori) {
    final kategoriKey = kategori.toLowerCase();
    return kategoriKey == 'foto' || kategoriKey == 'video';
  }
}